### ISSUE TITLE
bot comment examples fmt

### ISSUE THREAD

**Issue by 4meta5** [sunshine-protocol/sunshine-bounty#124]

**Comment by sunshine-bors** [comment]
$4444 Bounty Posted on Sunshine Chain With BountyId: 1

**Comment by sunshine-bors** [comment]
$333 Milestone Submitted on Sunshine Chain with MilestoneId: (1, 1)

**Comment by sunshine-bors** [comment]
$1738 Bounty Posted On Chain, BountyId 1

**Comment by sunshine-bors** [comment]
Contribution to Bounty 1 of Balance $10 increases Total Bounty Balance to $1748

**Comment by sunshine-bors** [comment]
$100 Submission for Bounty with SubmissionId 1 | [Submission Reference](https://github.com/sunshine-protocol/sunshine-bounty/issues/141)

**Comment by sunshine-bors** [comment]
$1 Remaining Balance for the Bounty after SubmissionId 1 approved for BountyId 100. Transferred Balance $1648 to the Submitter | [Submission Reference](https://github.com/sunshine-protocol/sunshine-bounty/issues/141)

**Comment by sunshine-bors** [comment]
$1738 Bounty Posted On Chain, BountyId 1

**Comment by sunshine-bors** [comment]
Contribution to Bounty 1 of Balance $10 increases Total Bounty Balance to $1748

**Comment by sunshine-bors** [comment]
$100 Submission for Bounty with SubmissionId 1 | [Submission Reference](https://github.com/sunshine-protocol/sunshine-bounty/issues/141)

**Comment by sunshine-bors** [comment]
$1 Remaining Balance for the Bounty after SubmissionId 1 approved for BountyId 100. Transferred Balance $1648 to the Submitter | [Submission Reference](https://github.com/sunshine-protocol/sunshine-bounty/issues/141)

**Comment by sunshine-bors** [comment]
$1738 Bounty Posted On Chain, BountyId 1

**Comment by sunshine-bors** [comment]
Contribution to Bounty 1 of Balance $10 increases Total Bounty Balance to $1748

**Comment by sunshine-bors** [comment]
$100 Submission for Bounty with SubmissionId 1 | [Submission Reference](https://github.com/sunshine-protocol/sunshine-bounty/issues/141)

**Comment by sunshine-bors** [comment]
$1648 Remaining Balance for the Bounty after SubmissionId 1 approved for BountyId 1. Transferred Balance $100 to the Submitter | [Submission Reference](https://github.com/sunshine-protocol/sunshine-bounty/issues/141)

**Comment by 4meta5** [comment]
Cool, will reopen if/when further testing is necessary

**Comment by sunshine-bors** [comment]
$1738 Bounty Posted On Chain, BountyId 1

**Comment by sunshine-bors** [comment]
Contribution to Bounty 1 of Balance $10 increases Total Bounty Balance to $1748

**Comment by sunshine-bors** [comment]
$100 Submission for Bounty with SubmissionId 1 | [Submission Reference](https://github.com/sunshine-protocol/sunshine-bounty/issues/141)

**Comment by sunshine-bors** [comment]
$1648 Remaining Balance for the Bounty after SubmissionId 1 approved for BountyId 1. Transferred Balance $100 to the Submitter | [Submission Reference](https://github.com/sunshine-protocol/sunshine-bounty/issues/141)

**Comment by sunshine-bors** [comment]
☀️ Sunshine Bounty Posted ☀️ 

                    BountyID: 1 | Total Amount: 1738

**Comment by sunshine-bors** [comment]
☀️ Sunshine Bounty Posted ☀️ 

                    BountyID: 1 | Total Amount: 1738

**Comment by sunshine-bors** [comment]
☀️ Sunshine Bounty Posted ☀️ 

                    BountyID: 1 | Total Amount: 1738

**Comment by sunshine-bors** [comment]
☀️ Sunshine Bounty Posted ☀️ 

                    BountyID: 1 | Total Amount: 1738

**Comment by sunshine-bors** [comment]
☀️ Sunshine Bounty Posted ☀️ 

                    BountyID: 1 | Total Amount: 1738

**Comment by sunshine-bors** [comment]
☀️ Sunshine Bounty Posted ☀️ 

                    BountyID: 1 | Total Amount: 1738

**Comment by sunshine-bors** [comment]
☀️ Sunshine Bounty Posted ☀️ 

                    BountyID: 1 | Total Amount: 1738
