### ISSUE TITLE
bot test issue

### ISSUE THREAD

**Issue by 4meta5** [sunshine-protocol/sunshine-bounty#141]

**Comment by sunshine-bors** [comment]
$100 Submission for BountyId 1 with SubmissionId 1 | [Bounty Reference](https://github.com/sunshine-protocol/sunshine-bounty/issues/124)

**Comment by sunshine-bors** [comment]
SubmissionId 1 approved for BountyId 1 and Transferred Balance $100 to the Submitter | [Bounty Reference](https://github.com/sunshine-protocol/sunshine-bounty/issues/124)

**Comment by sunshine-bors** [comment]
$100 Submission for BountyId 1 with SubmissionId 1 | [Bounty Reference](https://github.com/sunshine-protocol/sunshine-bounty/issues/124)

**Comment by sunshine-bors** [comment]
SubmissionId 1 approved for BountyId 1 and Transferred Balance $100 to the Submitter | [Bounty Reference](https://github.com/sunshine-protocol/sunshine-bounty/issues/124)

**Comment by sunshine-bors** [comment]
$100 Submission for BountyId 1 with SubmissionId 1 | [Bounty Reference](https://github.com/sunshine-protocol/sunshine-bounty/issues/124)

**Comment by sunshine-bors** [comment]
SubmissionId 1 approved for BountyId 1 and Transferred Balance $100 to the Submitter | [Bounty Reference](https://github.com/sunshine-protocol/sunshine-bounty/issues/124)

**Comment by 4meta5** [comment]
Cool, will reopen if/when further testing is necessary

**Comment by sunshine-bors** [comment]
$100 Submission for BountyId 1 with SubmissionId 1 | [Bounty Reference](https://github.com/sunshine-protocol/sunshine-bounty/issues/124)

**Comment by sunshine-bors** [comment]
SubmissionId 1 approved for BountyId 1 and Transferred Balance $100 to the Submitter | [Bounty Reference](https://github.com/sunshine-protocol/sunshine-bounty/issues/124)
