### ISSUE TITLE
Genesis configuration for donations

### ISSUE THREAD

**Issue by ltfschoen** [sunshine-protocol/sunshine-bounty#149]
When I reviewed the genesis configuration I was wondering why it didn't set a default recipient pool account (i.e. a choice of pool accounts governed by the community members associated with different causes)

**Comment by 4meta5** [comment]
There is an org at genesis which contains accounts [here](https://github.com/sunshine-protocol/sunshine-bounty/blob/master/bin/node/src/chain_spec.rs#L169). We could make this Org weighted but it is flat right now (every account in the org has the same weight). The `donate` module contains the functionality to transfer to an Org in proportion to ownership weight (or with equal weight). So what you're describing is a possible feature if added to the interface at genesis to encourage donations to these accounts.
