### ISSUE TITLE
demo bounty issue

### ISSUE THREAD

**Issue by 4meta5** [sunshine-protocol/sunshine-bounty#160]

**Comment by dvc94ch** [comment]
The bot should update it's comment instead of spamming the issue. If you have 10 submitters, no one will understand anything. See how gitcoin bot does it

**Comment by 4meta5** [comment]
The bot creates comments. It doesn't recognize comments and update them. That would be an additional feature which we can make a separate issue for in `sunshine-bounty` where `client/gbot` lives (the library that wraps Octocrab).

The local demo shows that the bot actually works, even if only in the context of the locally run dev chain. **Everyone running the local demo runs their own chain from scratch.** Of course, it doesn't connect to some testnet so no existing chain state is being updated. The live testnet shows how the live testnet bot works, but that isn't the purpose of this issue or this repository.
