### ISSUE TITLE
update bot comments when possible

### ISSUE THREAD

**Issue by 4meta5** [sunshine-protocol/sunshine-bounty#162]
The bot should update it's comment instead of spamming the issue. If you have 10 submitters, no one will understand anything. See how gitcoin bot does it

_Originally posted by @dvc94ch in https://github.com/sunshine-protocol/sunshine-bounty/issues/160#issuecomment-674386810_

**feature request** for `client/gbot` to read and update existing comments by itself if they exist

**Comment by sunshine-bors** [comment]
☀️ Sunshine Bounty Posted ☀️ 

                    BountyID: 2 | Total Amount: 1234

**Comment by sunshine-bors** [comment]
## ☀️ Sunshine Bounty Posted ☀️ <br>
                    BountyID: 2 | Total Amount: 1234

**Comment by sunshine-bors** [comment]
## ☀️ Sunshine Bounty Posted ☀️ <br>
                    BountyID: 2 | Total Amount: 1234

**Comment by sunshine-bors** [comment]
## ☀️ Sunshine Bounty Posted ☀️ <br> BountyID: 2 | Total Amount: 1234

**Comment by sunshine-bors** [comment]
## ☀️ Sunshine Bounty Posted ☀️ <br> BountyID: 2 🌻 Total Amount: 1234

**Comment by sunshine-bors** [comment]
## ☀️ Sunshine Bounty Posted ☀️ <br> BountyID: 2 🌻 Total Amount: 1234
