### ISSUE TITLE
running cargo clippy in the CI

### ISSUE THREAD

**Issue by 4meta5** [sunshine-protocol/sunshine-bounty#38]
I'm commenting the following out of the CI because I can't resolve the error that it emits

```
- name: cargo clippy
  run: cargo clippy -- -D warnings
```

```rust
error: this public function dereferences a raw pointer but is not marked `unsafe`
   --> /home/runner/work/sunshine-node/sunshine-node/runtime/src/lib.rs:288:1
    |
288 | / impl_runtime_apis! {
289 | |     impl sp_api::Core<Block> for Runtime {
290 | |         fn version() -> RuntimeVersion {
291 | |             VERSION
...   |
376 | |     }
377 | | }
    | | ^ in this macro invocation
    | |_|
    | 
    |
    = note: `#[deny(clippy::not_unsafe_ptr_arg_deref)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#not_unsafe_ptr_arg_deref
```

I've already tried 
* add `#![allow(clippy::not_unsafe_ptr_arg_deref)]` to the top of the file and it won't allow me to add an outer attribute followed by an inner attribute (the recursion limit)
* add `#![allow(clippy::not_unsafe_ptr_arg_deref)]` to the `build.rs` file which doesn't do anything
* making the function `unsafe` which creates an error because the trait that is implemented does not mark this method as unsafe
* creating an unsafe block around `VERSION` which also isn't allowed -- building it gives me me another error

## decision

should get in the habit of running this locally but I won't accept a permanent red X on the CI indicator when everything else works, it's just bad vibes (_the color of the red X was designed to coax developers towards the green check_) SO I'm taking it out for now

It would be nice if I could pass a flag into the cargo clippy command to ignore this warning

**Comment by dvc94ch** [comment]
I guess this can be closed?

**Comment by 4meta5** [comment]
ye
