### ISSUE TITLE
add debug script for running node that uses `-lruntime=debug`

### ISSUE THREAD

**Issue by 4meta5** [sunshine-protocol/sunshine-bounty#41]
run node with `-lruntime=debug` to print the error instead of getting something like `system:ExtrinsicFailed:: (phase={"ApplyExtrinsic":2}) shared.ts?3413:309
DispatchError: {"Module":{"index":24,"error":0}}`

**Comment by 4meta5** [comment]
To check if the code compiles to `wasm` without the anxiety of delayed linker errors, compile to the target here https://github.com/therealprof/atsamd20e15a `thumb7m-none-eabi` instead of `wasm32-unknown-unknown`

**Comment by dvc94ch** [comment]
I guess this one can be closed too?

**Comment by 4meta5** [comment]
ye
